cd C:%HOMEPATH%\AppData\Local\Roblox\Versions
for  /F "delims=" %%i IN ('dir /b /ad-h /t:c /od') do set p=%%i
if defined p (
echo using %p%
) else (
    echo file not found
)
cd C:%HOMEPATH%\AppData\Local\Roblox\Versions\%p%
if exist ClientSettings\ (
    echo Client Settings subdir found
) else (
    echo subdir not found
    md ClientSettings
)
cd C:%HOMEPATH%\AppData\Local\Roblox\Versions\%p%\ClientSettings
if exist bottom.txt (
    echo bottom.txt present
) else (
echo  "FStringFlagUpdateVersion": "139 Beta - Version 14", >> C:%HOMEPATH%\AppData\Local\Roblox\Versions\%p%\ClientSettings\bottom.txt
echo  "DFIntSecondsBetweenDynamicVariableReloading": 31557600, >> C:%HOMEPATH%\AppData\Local\Roblox\Versions\%p%\ClientSettings\bottom.txt
echo  "FIntRolloutEnrollmentExpirationMinutes": 525949, >> C:%HOMEPATH%\AppData\Local\Roblox\Versions\%p%\ClientSettings\bottom.txt
echo  "DFFlagDynamicFastVariableReloaderTest1": false, >> C:%HOMEPATH%\AppData\Local\Roblox\Versions\%p%\ClientSettings\bottom.txt
echo  "FFlagExecDynInitTests": false, >> C:%HOMEPATH%\AppData\Local\Roblox\Versions\%p%\ClientSettings\bottom.txt
echo  "DFFlagEarlyExitIfHang": false, >> C:%HOMEPATH%\AppData\Local\Roblox\Versions\%p%\ClientSettings\bottom.txt
echo  "FIntTerrainOTAMaxTextureSize": 1024, >> C:%HOMEPATH%\AppData\Local\Roblox\Versions\%p%\ClientSettings\bottom.txt
echo  "FIntUITextureMaxRenderTextureSize": 1024, >> C:%HOMEPATH%\AppData\Local\Roblox\Versions\%p%\ClientSettings\bottom.txt
echo  "FIntMaxCachedPatches": 2, >> C:%HOMEPATH%\AppData\Local\Roblox\Versions\%p%\ClientSettings\bottom.txt
echo  "FIntTaskSchedulerAutoThreadLimit": 16, >> C:%HOMEPATH%\AppData\Local\Roblox\Versions\%p%\ClientSettings\bottom.txt
echo  "FIntMeshContentProviderForceCacheSize": 268435456, >> C:%HOMEPATH%\AppData\Local\Roblox\Versions\%p%\ClientSettings\bottom.txt
echo  "FIntDefaultMeshCacheSizeMB": 256, >> C:%HOMEPATH%\AppData\Local\Roblox\Versions\%p%\ClientSettings\bottom.txt
echo  "DFIntHttpCurlConnectionCacheSize": 134217728, >> C:%HOMEPATH%\AppData\Local\Roblox\Versions\%p%\ClientSettings\bottom.txt
echo  "DFIntHttpCurlMaxConnectionsPerHost": 32, >> C:%HOMEPATH%\AppData\Local\Roblox\Versions\%p%\ClientSettings\bottom.txt
echo  "DFIntHttpConnMaxAge": 3600, >> C:%HOMEPATH%\AppData\Local\Roblox\Versions\%p%\ClientSettings\bottom.txt
echo  "DFIntHttpCacheRetryCount": 4, >> C:%HOMEPATH%\AppData\Local\Roblox\Versions\%p%\ClientSettings\bottom.txt
echo  "DFIntHttpCacheRefreshHundredthsPercent": 75, >> C:%HOMEPATH%\AppData\Local\Roblox\Versions\%p%\ClientSettings\bottom.txt
echo  "DFIntExternalHttpRequestSizeLimitKB": 16384,   >> C:%HOMEPATH%\AppData\Local\Roblox\Versions\%p%\ClientSettings\bottom.txt
echo  "DFIntHttpBatchApi_maxReqs": 4, >> C:%HOMEPATH%\AppData\Local\Roblox\Versions\%p%\ClientSettings\bottom.txt
echo  "DFIntHttpMaxRedirects": 6, >> C:%HOMEPATH%\AppData\Local\Roblox\Versions\%p%\ClientSettings\bottom.txt
echo  "DFIntHttpMaxRetries": 4, >> C:%HOMEPATH%\AppData\Local\Roblox\Versions\%p%\ClientSettings\bottom.txt
echo  "DFFlagHttpCacheCleanBasedOnMemory": true,   >> C:%HOMEPATH%\AppData\Local\Roblox\Versions\%p%\ClientSettings\bottom.txt
echo  "DFFlagEnableHttpCacheForceRevalidate2": false, >> C:%HOMEPATH%\AppData\Local\Roblox\Versions\%p%\ClientSettings\bottom.txt
echo  "FIntEmotesAnimationsPerPlayerCacheSize": 16777216, >> C:%HOMEPATH%\AppData\Local\Roblox\Versions\%p%\ClientSettings\bottom.txt
echo  "DFIntUserIdPlayerNameCacheSize": 33554432, >> C:%HOMEPATH%\AppData\Local\Roblox\Versions\%p%\ClientSettings\bottom.txt
echo  "DFIntUserIdPlayerNameLifetimeSeconds": 86400, >> C:%HOMEPATH%\AppData\Local\Roblox\Versions\%p%\ClientSettings\bottom.txt
echo  "FIntHttpCurlMaxCachedHandlesPerHost": 16, >> C:%HOMEPATH%\AppData\Local\Roblox\Versions\%p%\ClientSettings\bottom.txt
echo  "FIntSSAOMipLevels": 0, >> C:%HOMEPATH%\AppData\Local\Roblox\Versions\%p%\ClientSettings\bottom.txt
echo  "DFIntJoinDataCompressionLevel": 2, >> C:%HOMEPATH%\AppData\Local\Roblox\Versions\%p%\ClientSettings\bottom.txt
echo  "DFIntClusterCompressionLevel": 2, >> C:%HOMEPATH%\AppData\Local\Roblox\Versions\%p%\ClientSettings\bottom.txt
echo  "DFIntNetworkSchemaCompressionRatio": 18, >> C:%HOMEPATH%\AppData\Local\Roblox\Versions\%p%\ClientSettings\bottom.txt
echo  "FFlagHandleAltEnterFullscreenManually": false, >> C:%HOMEPATH%\AppData\Local\Roblox\Versions\%p%\ClientSettings\bottom.txt
echo  "FFlagEnableQuickGameLaunch": true, >> C:%HOMEPATH%\AppData\Local\Roblox\Versions\%p%\ClientSettings\bottom.txt
echo  "FFlagPreloadAllFonts": true, >> C:%HOMEPATH%\AppData\Local\Roblox\Versions\%p%\ClientSettings\bottom.txt
echo  "FFlagPreloadMinimalFonts": true, >> C:%HOMEPATH%\AppData\Local\Roblox\Versions\%p%\ClientSettings\bottom.txt
echo  "FFlagPreloadTextureItemsOption4": true, >> C:%HOMEPATH%\AppData\Local\Roblox\Versions\%p%\ClientSettings\bottom.txt
echo  "FFlagBatchAssetApi": true, >> C:%HOMEPATH%\AppData\Local\Roblox\Versions\%p%\ClientSettings\bottom.txt
echo  "DFLogBatchAssetApiLog": 6, >> C:%HOMEPATH%\AppData\Local\Roblox\Versions\%p%\ClientSettings\bottom.txt
echo  "FFlagEnableZeroLatencyCacheForVersionedAssets": true, >> C:%HOMEPATH%\AppData\Local\Roblox\Versions\%p%\ClientSettings\bottom.txt
echo  "FFlagFinishFetchingAssetsCorrectly": true, >> C:%HOMEPATH%\AppData\Local\Roblox\Versions\%p%\ClientSettings\bottom.txt
echo  "FFlagAnimationClipMemCacheEnabled": true, >> C:%HOMEPATH%\AppData\Local\Roblox\Versions\%p%\ClientSettings\bottom.txt
echo  "FFlagCacheRequestedMaxSize": true, >> C:%HOMEPATH%\AppData\Local\Roblox\Versions\%p%\ClientSettings\bottom.txt
echo  "FFlagGraphicsD3D11AllowThreadSafeTextureUpload": true, >> C:%HOMEPATH%\AppData\Local\Roblox\Versions\%p%\ClientSettings\bottom.txt
echo  "FFlagGraphicsEnableD3D10Compute": true, >> C:%HOMEPATH%\AppData\Local\Roblox\Versions\%p%\ClientSettings\bottom.txt
echo  "FFlagGraphicsTextureCopy": true, >> C:%HOMEPATH%\AppData\Local\Roblox\Versions\%p%\ClientSettings\bottom.txt
echo  "DFFlagAlwaysPutSoundsOnDiskWhenLowOnMemory": true, >> C:%HOMEPATH%\AppData\Local\Roblox\Versions\%p%\ClientSettings\bottom.txt
echo  "FFlagUpdateUICachesWithQuadTree3": true, >> C:%HOMEPATH%\AppData\Local\Roblox\Versions\%p%\ClientSettings\bottom.txt
echo  "DFFlagExperimentalRuntimeTextureCreation": true, >> C:%HOMEPATH%\AppData\Local\Roblox\Versions\%p%\ClientSettings\bottom.txt
echo  "FFlagFixGraphicsQuality": true, >> C:%HOMEPATH%\AppData\Local\Roblox\Versions\%p%\ClientSettings\bottom.txt
echo  "FFlagCommitToGraphicsQualityFix": true, >> C:%HOMEPATH%\AppData\Local\Roblox\Versions\%p%\ClientSettings\bottom.txt
echo  "FFlagFixTextureCompositorFramebufferManagement2": true, >> C:%HOMEPATH%\AppData\Local\Roblox\Versions\%p%\ClientSettings\bottom.txt
echo  "DFFlagQueueDataPingFromSendData": true, >> C:%HOMEPATH%\AppData\Local\Roblox\Versions\%p%\ClientSettings\bottom.txt
echo  "FFlagDontCreatePingJob": true, >> C:%HOMEPATH%\AppData\Local\Roblox\Versions\%p%\ClientSettings\bottom.txt
echo  "FFlagRenderGpuTextureCompressor": true, >> C:%HOMEPATH%\AppData\Local\Roblox\Versions\%p%\ClientSettings\bottom.txt
echo  "DFIntRenderingThrottleDelayInMS": 20, >> C:%HOMEPATH%\AppData\Local\Roblox\Versions\%p%\ClientSettings\bottom.txt
echo  "FFlagHumanoidParallelFasterSetCollision": true, >> C:%HOMEPATH%\AppData\Local\Roblox\Versions\%p%\ClientSettings\bottom.txt
echo  "FFlagHumanoidParallelFasterWakeUp": true, >> C:%HOMEPATH%\AppData\Local\Roblox\Versions\%p%\ClientSettings\bottom.txt
echo  "FFlagHumanoidParallelFixTickleFloor2": true, >> C:%HOMEPATH%\AppData\Local\Roblox\Versions\%p%\ClientSettings\bottom.txt
echo  "FFlagHumanoidParallelOnStep2": true, >> C:%HOMEPATH%\AppData\Local\Roblox\Versions\%p%\ClientSettings\bottom.txt
echo  "FFlagHumanoidParallelSafeCofmUpdate": true, >> C:%HOMEPATH%\AppData\Local\Roblox\Versions\%p%\ClientSettings\bottom.txt
echo  "FFlagHumanoidParallelSafeUnseat": true, >> C:%HOMEPATH%\AppData\Local\Roblox\Versions\%p%\ClientSettings\bottom.txt
echo  "FFlagHumanoidParallelUseManager4": true, >> C:%HOMEPATH%\AppData\Local\Roblox\Versions\%p%\ClientSettings\bottom.txt
echo  "FIntClientCompressionFormatRequestPC": 3, >> C:%HOMEPATH%\AppData\Local\Roblox\Versions\%p%\ClientSettings\bottom.txt
echo  "DFFlagThrottleDeveloperConsoleEvents": true, >> C:%HOMEPATH%\AppData\Local\Roblox\Versions\%p%\ClientSettings\bottom.txt
echo  "FFlagFastGPULightCulling3": true, >> C:%HOMEPATH%\AppData\Local\Roblox\Versions\%p%\ClientSettings\bottom.txt
echo  "FFlagDebugForceFSMCPULightCulling": true, >> C:%HOMEPATH%\AppData\Local\Roblox\Versions\%p%\ClientSettings\bottom.txt
echo  "FFlagUseMediumpSamplers": true, >> C:%HOMEPATH%\AppData\Local\Roblox\Versions\%p%\ClientSettings\bottom.txt
echo  "DFFlagPredictedOOM": false, >> C:%HOMEPATH%\AppData\Local\Roblox\Versions\%p%\ClientSettings\bottom.txt
echo  "DFFlagPredictedOOMAbs": false, >> C:%HOMEPATH%\AppData\Local\Roblox\Versions\%p%\ClientSettings\bottom.txt
echo  "DFFlagUsePredictedOOMAbsLimitForMemoryCurve": false, >> C:%HOMEPATH%\AppData\Local\Roblox\Versions\%p%\ClientSettings\bottom.txt
echo  "DFFlagOOMTimestamp2": false, >> C:%HOMEPATH%\AppData\Local\Roblox\Versions\%p%\ClientSettings\bottom.txt
echo  "DFIntInferredOOMUsedMemHundredthsPercent": 0, >> C:%HOMEPATH%\AppData\Local\Roblox\Versions\%p%\ClientSettings\bottom.txt
echo  "DFIntPredictedOOMPercent": 0, >> C:%HOMEPATH%\AppData\Local\Roblox\Versions\%p%\ClientSettings\bottom.txt
echo  "FFlagCacheHardwareInfo": true, >> C:%HOMEPATH%\AppData\Local\Roblox\Versions\%p%\ClientSettings\bottom.txt
echo  "DFLogHttpTrace": 0, >> C:%HOMEPATH%\AppData\Local\Roblox\Versions\%p%\ClientSettings\bottom.txt
echo  "DFLogHttpTraceError": 0, >> C:%HOMEPATH%\AppData\Local\Roblox\Versions\%p%\ClientSettings\bottom.txt
echo  "DFLogHttpTraceLight": 0, >> C:%HOMEPATH%\AppData\Local\Roblox\Versions\%p%\ClientSettings\bottom.txt
echo  "DFFlagEnableLuobuCDNDomain": false, >> C:%HOMEPATH%\AppData\Local\Roblox\Versions\%p%\ClientSettings\bottom.txt
echo  "DFFlagEnableLuobuServiceDomain": false, >> C:%HOMEPATH%\AppData\Local\Roblox\Versions\%p%\ClientSettings\bottom.txt
echo  "FFlagLuobuLuaAuthEnabled": false, >> C:%HOMEPATH%\AppData\Local\Roblox\Versions\%p%\ClientSettings\bottom.txt
echo  "FFlagLuobuModerationStatusAvailable": false, >> C:%HOMEPATH%\AppData\Local\Roblox\Versions\%p%\ClientSettings\bottom.txt
echo  "FStringFeature_LuobuLuaAuthEnabled": "0;0", >> C:%HOMEPATH%\AppData\Local\Roblox\Versions\%p%\ClientSettings\bottom.txt
echo  "DFFlagEnableRobloxCNDomains": false, >> C:%HOMEPATH%\AppData\Local\Roblox\Versions\%p%\ClientSettings\bottom.txt
echo  "DFIntSendJoinTimeDeltasToDiagLuobu_HundredthsPercentage": 0, >> C:%HOMEPATH%\AppData\Local\Roblox\Versions\%p%\ClientSettings\bottom.txt
echo  "DFIntSendJoinTimeStatsHundPrecLuobuOverride": 0, >> C:%HOMEPATH%\AppData\Local\Roblox\Versions\%p%\ClientSettings\bottom.txt
echo  "DFFlagEnableExtraUnreachableTelemetry": false, >> C:%HOMEPATH%\AppData\Local\Roblox\Versions\%p%\ClientSettings\bottom.txt
echo  "DFIntPercentileTelemetryHundredPercent": 0, >> C:%HOMEPATH%\AppData\Local\Roblox\Versions\%p%\ClientSettings\bottom.txt
echo  "DFFlagEnablePercentileTelemetry": false, >> C:%HOMEPATH%\AppData\Local\Roblox\Versions\%p%\ClientSettings\bottom.txt
echo  "DFIntSendAvatarLoadTimeStats_HundredthsPercentage": 0, >> C:%HOMEPATH%\AppData\Local\Roblox\Versions\%p%\ClientSettings\bottom.txt
echo  "DFIntSendHttpRbxApiStatsToDiag_HundredthsPercentage": 0, >> C:%HOMEPATH%\AppData\Local\Roblox\Versions\%p%\ClientSettings\bottom.txt
echo  "DFIntSendJoinHttpBytesToDiag_HundredthsPercentage": 0, >> C:%HOMEPATH%\AppData\Local\Roblox\Versions\%p%\ClientSettings\bottom.txt
echo  "DFIntSendJoinTimeDeltasToDiag_HundredthsPercentage": 0, >> C:%HOMEPATH%\AppData\Local\Roblox\Versions\%p%\ClientSettings\bottom.txt
echo  "DFIntSendJoinTimeStatsToDiag_HundredthsPercentage": 0, >> C:%HOMEPATH%\AppData\Local\Roblox\Versions\%p%\ClientSettings\bottom.txt
echo  "DFIntSendJoinTimesToDiag_HundredthsPercentage": 0, >> C:%HOMEPATH%\AppData\Local\Roblox\Versions\%p%\ClientSettings\bottom.txt
echo  "DFFlagEnableLogServiceCounter": false, >> C:%HOMEPATH%\AppData\Local\Roblox\Versions\%p%\ClientSettings\bottom.txt
echo  "DFFlagPhysicsReceiveReportPerfData2": false, >> C:%HOMEPATH%\AppData\Local\Roblox\Versions\%p%\ClientSettings\bottom.txt
echo  "DFFlagPhysicsAnalytics": false, >> C:%HOMEPATH%\AppData\Local\Roblox\Versions\%p%\ClientSettings\bottom.txt
echo  "DFFlagProximityPromptAnalytics": false, >> C:%HOMEPATH%\AppData\Local\Roblox\Versions\%p%\ClientSettings\bottom.txt
echo  "DFFlagCountOldChatAPIUsageV2": false, >> C:%HOMEPATH%\AppData\Local\Roblox\Versions\%p%\ClientSettings\bottom.txt
echo  "DFFlagStoreUniqueIdInferredCrashSystem": false, >> C:%HOMEPATH%\AppData\Local\Roblox\Versions\%p%\ClientSettings\bottom.txt
echo  "FFlagWindowsLaunchTypeAnalytics": false, >> C:%HOMEPATH%\AppData\Local\Roblox\Versions\%p%\ClientSettings\bottom.txt
echo  "FFlagTrackPlaceIdForCrashEnabled": false, >> C:%HOMEPATH%\AppData\Local\Roblox\Versions\%p%\ClientSettings\bottom.txt
echo  "GoogleAnalyticsAccountPropertyID": "opt-out", >> C:%HOMEPATH%\AppData\Local\Roblox\Versions\%p%\ClientSettings\bottom.txt
echo  "FFlagNFDN2644ExplicitlyConstructCrashReporterInStartup": false, >> C:%HOMEPATH%\AppData\Local\Roblox\Versions\%p%\ClientSettings\bottom.txt
echo  "DFFlagEnableMemProfilingStorePlaceId": false, >> C:%HOMEPATH%\AppData\Local\Roblox\Versions\%p%\ClientSettings\bottom.txt
echo  "DFFlagChatFloodCheckEnableEventCounters": false, >> C:%HOMEPATH%\AppData\Local\Roblox\Versions\%p%\ClientSettings\bottom.txt
echo  "DFFlagChatFloodCheckEnableEventIngest": false, >> C:%HOMEPATH%\AppData\Local\Roblox\Versions\%p%\ClientSettings\bottom.txt
echo  "DFFlagEnableMemProfilingOutsideClient": false, >> C:%HOMEPATH%\AppData\Local\Roblox\Versions\%p%\ClientSettings\bottom.txt
echo  "DFFlagIncludeFreeOsMemAndOtherTelemetryForHarmony": false, >> C:%HOMEPATH%\AppData\Local\Roblox\Versions\%p%\ClientSettings\bottom.txt
echo  "BuildVariantInBacktrace": false, >> C:%HOMEPATH%\AppData\Local\Roblox\Versions\%p%\ClientSettings\bottom.txt
echo  "DFFlagCrashUploadFullDumps": false, >> C:%HOMEPATH%\AppData\Local\Roblox\Versions\%p%\ClientSettings\bottom.txt
echo  "HttpDetailedLogging": false, >> C:%HOMEPATH%\AppData\Local\Roblox\Versions\%p%\ClientSettings\bottom.txt
echo  "DFFlagHttpReportAnalyticsTelem": false, >> C:%HOMEPATH%\AppData\Local\Roblox\Versions\%p%\ClientSettings\bottom.txt
echo  "DFFlagMemoryPressureGCStats": false, >> C:%HOMEPATH%\AppData\Local\Roblox\Versions\%p%\ClientSettings\bottom.txt
echo  "DFFlagOsVersionWin32": false, >> C:%HOMEPATH%\AppData\Local\Roblox\Versions\%p%\ClientSettings\bottom.txt
echo  "FFlagEnableBacktraceMissingLogReport": false, >> C:%HOMEPATH%\AppData\Local\Roblox\Versions\%p%\ClientSettings\bottom.txt
echo  "DFStringCrashUploadToBacktraceTestingToken": "opt-out", >> C:%HOMEPATH%\AppData\Local\Roblox\Versions\%p%\ClientSettings\bottom.txt
echo  "DFStringCrashUploadToBacktraceMacPlayerToken": "opt-out", >> C:%HOMEPATH%\AppData\Local\Roblox\Versions\%p%\ClientSettings\bottom.txt
echo  "DFStringCrashUploadToBacktraceWindowsPlayerToken": "opt-out", >> C:%HOMEPATH%\AppData\Local\Roblox\Versions\%p%\ClientSettings\bottom.txt
echo  "FStringCoreScriptBacktraceErrorUploadToken": "opt-out", >> C:%HOMEPATH%\AppData\Local\Roblox\Versions\%p%\ClientSettings\bottom.txt
echo  "FFlagWin32CrashUploadRobloxTelemetry": false, >> C:%HOMEPATH%\AppData\Local\Roblox\Versions\%p%\ClientSettings\bottom.txt
echo  "FStringGamesUrlPath": "/games/", >> C:%HOMEPATH%\AppData\Local\Roblox\Versions\%p%\ClientSettings\bottom.txt
echo  "DFFlagAddPublicGettersForGfxQualityAndFpsForTelemCounters2": false, >> C:%HOMEPATH%\AppData\Local\Roblox\Versions\%p%\ClientSettings\bottom.txt
echo  "GoogleAnalyticsAccountPropertyIDPlayer": "opt-out", >> C:%HOMEPATH%\AppData\Local\Roblox\Versions\%p%\ClientSettings\bottom.txt
echo  "DFFlagAdditionalUWPCrashReportData": false, >> C:%HOMEPATH%\AppData\Local\Roblox\Versions\%p%\ClientSettings\bottom.txt
echo  "DFFlagAddGlobalAnalyticsPlaySessionId": false, >> C:%HOMEPATH%\AppData\Local\Roblox\Versions\%p%\ClientSettings\bottom.txt
echo  "DFFlagEnableRolloutFlagCrashDataUWP": false, >> C:%HOMEPATH%\AppData\Local\Roblox\Versions\%p%\ClientSettings\bottom.txt
echo  "DFFlagEnableRolloutFlagCrashDataMacClient": false, >> C:%HOMEPATH%\AppData\Local\Roblox\Versions\%p%\ClientSettings\bottom.txt
echo  "DFFlagCrashpadReportGfx": false, >> C:%HOMEPATH%\AppData\Local\Roblox\Versions\%p%\ClientSettings\bottom.txt
echo  "DFFlagEnableHumanoidStateChangeTelemtry": false, >> C:%HOMEPATH%\AppData\Local\Roblox\Versions\%p%\ClientSettings\bottom.txt
echo  "FFlagContactImporterAddBacktraceAttribute": false, >> C:%HOMEPATH%\AppData\Local\Roblox\Versions\%p%\ClientSettings\bottom.txt
echo  "FFlagEnableBacktraceAttachmentsV3": false, >> C:%HOMEPATH%\AppData\Local\Roblox\Versions\%p%\ClientSettings\bottom.txt
echo  "FFlagUserAgentInBacktraceReports": false, >> C:%HOMEPATH%\AppData\Local\Roblox\Versions\%p%\ClientSettings\bottom.txt
echo  "DFFlagEnableHumanoidStateChangeTelemtryOldStateDuration": false, >> C:%HOMEPATH%\AppData\Local\Roblox\Versions\%p%\ClientSettings\bottom.txt
echo  "DFFlagLegacyRedundantPlayerCheckAnalytics": false, >> C:%HOMEPATH%\AppData\Local\Roblox\Versions\%p%\ClientSettings\bottom.txt
echo  "FFlagEnableReportAnythingAnalytics": false, >> C:%HOMEPATH%\AppData\Local\Roblox\Versions\%p%\ClientSettings\bottom.txt
echo  "DFFlagAddAdditionalTagsEventIngest2": false, >> C:%HOMEPATH%\AppData\Local\Roblox\Versions\%p%\ClientSettings\bottom.txt
echo  "DFFlagAddGlobalWindToPlaceStats": false, >> C:%HOMEPATH%\AppData\Local\Roblox\Versions\%p%\ClientSettings\bottom.txt
echo  "DFFlagAddLightingToPlaceStats": false, >> C:%HOMEPATH%\AppData\Local\Roblox\Versions\%p%\ClientSettings\bottom.txt
echo  "DFFlagAddStreamingEnabledTagEventIngest": false, >> C:%HOMEPATH%\AppData\Local\Roblox\Versions\%p%\ClientSettings\bottom.txt
echo  "DFFlagAMPTelemetryPoints": false, >> C:%HOMEPATH%\AppData\Local\Roblox\Versions\%p%\ClientSettings\bottom.txt
echo  "DFFlagAMPTelemetryUser": false, >> C:%HOMEPATH%\AppData\Local\Roblox\Versions\%p%\ClientSettings\bottom.txt
echo  "DFFlagAUMPAnalytics": false, >> C:%HOMEPATH%\AppData\Local\Roblox\Versions\%p%\ClientSettings\bottom.txt
echo  "DFFlagAttachmentCrashReport": false, >> C:%HOMEPATH%\AppData\Local\Roblox\Versions\%p%\ClientSettings\bottom.txt
echo  "FFlagEnableBacktraceResponseHandler": false, >> C:%HOMEPATH%\AppData\Local\Roblox\Versions\%p%\ClientSettings\bottom.txt
echo  "FFlagEnableBacktraceConnectionDidFailHandler": false, >> C:%HOMEPATH%\AppData\Local\Roblox\Versions\%p%\ClientSettings\bottom.txt
echo  "FFlagEnableBatteryStateLogger": false, >> C:%HOMEPATH%\AppData\Local\Roblox\Versions\%p%\ClientSettings\bottom.txt
echo  "FIntLuaAppBacktraceErrorReportPercentage": 0, >> C:%HOMEPATH%\AppData\Local\Roblox\Versions\%p%\ClientSettings\bottom.txt
echo  "FFlagWin32BacktraceWindowsLaunchType": false, >> C:%HOMEPATH%\AppData\Local\Roblox\Versions\%p%\ClientSettings\bottom.txt
echo  "FIntBacktraceUseSyncPercentage": 0, >> C:%HOMEPATH%\AppData\Local\Roblox\Versions\%p%\ClientSettings\bottom.txt
echo  "FIntAbuseReportScreenshotMaxSize": 0, >> C:%HOMEPATH%\AppData\Local\Roblox\Versions\%p%\ClientSettings\bottom.txt
echo  "DFIntCrashReportingHundredthsPercentage": 0, >> C:%HOMEPATH%\AppData\Local\Roblox\Versions\%p%\ClientSettings\bottom.txt
echo  "DFIntCrashUploadErrorInfluxHundredthsPercentage": 0, >> C:%HOMEPATH%\AppData\Local\Roblox\Versions\%p%\ClientSettings\bottom.txt
echo  "DFIntCrashUploadToBacktracePercentage": 0, >> C:%HOMEPATH%\AppData\Local\Roblox\Versions\%p%\ClientSettings\bottom.txt
echo  "DFIntWriteFullDmpPercent": 0, >> C:%HOMEPATH%\AppData\Local\Roblox\Versions\%p%\ClientSettings\bottom.txt
echo  "DFFlagSafetyServiceScreenshot": false, >> C:%HOMEPATH%\AppData\Local\Roblox\Versions\%p%\ClientSettings\bottom.txt
echo  "DFFlagESGamePerfMonitorEnabled": false, >> C:%HOMEPATH%\AppData\Local\Roblox\Versions\%p%\ClientSettings\bottom.txt
echo  "DFIntESGamePerfMonitorHundredthsPercentage": 0, >> C:%HOMEPATH%\AppData\Local\Roblox\Versions\%p%\ClientSettings\bottom.txt
echo  "FIntGamePerfMonitorPercentage": 0, >> C:%HOMEPATH%\AppData\Local\Roblox\Versions\%p%\ClientSettings\bottom.txt
echo  "DFFlagEnablePerfAudioCollection": false, >> C:%HOMEPATH%\AppData\Local\Roblox\Versions\%p%\ClientSettings\bottom.txt
echo  "DFFlagEnablePerfDataCoreCategoryTimersCollection2": false, >> C:%HOMEPATH%\AppData\Local\Roblox\Versions\%p%\ClientSettings\bottom.txt
echo  "DFFlagEnablePerfDataCoreTimersCollection2": false, >> C:%HOMEPATH%\AppData\Local\Roblox\Versions\%p%\ClientSettings\bottom.txt
echo  "DFFlagEnablePerfDataCountersCollection": false, >> C:%HOMEPATH%\AppData\Local\Roblox\Versions\%p%\ClientSettings\bottom.txt
echo  "DFFlagEnablePerfDataGatherTelemetry2": false, >> C:%HOMEPATH%\AppData\Local\Roblox\Versions\%p%\ClientSettings\bottom.txt
echo  "DFFlagEnablePerfDataMemoryCategoriesCollection2": false, >> C:%HOMEPATH%\AppData\Local\Roblox\Versions\%p%\ClientSettings\bottom.txt
echo  "DFFlagEnablePerfDataMemoryCollection": false, >> C:%HOMEPATH%\AppData\Local\Roblox\Versions\%p%\ClientSettings\bottom.txt
echo  "DFFlagEnablePerfDataMemoryPerformanceCleanup3": false, >> C:%HOMEPATH%\AppData\Local\Roblox\Versions\%p%\ClientSettings\bottom.txt
echo  "DFFlagEnablePerfDataMemoryPressureCollection": false, >> C:%HOMEPATH%\AppData\Local\Roblox\Versions\%p%\ClientSettings\bottom.txt
echo  "DFFlagEnablePerfDataReportThermals": false, >> C:%HOMEPATH%\AppData\Local\Roblox\Versions\%p%\ClientSettings\bottom.txt
echo  "DFFlagEnablePerfDataSubsystemTimersCollection2": false, >> C:%HOMEPATH%\AppData\Local\Roblox\Versions\%p%\ClientSettings\bottom.txt
echo  "DFFlagEnablePerfDataSummaryMode": false, >> C:%HOMEPATH%\AppData\Local\Roblox\Versions\%p%\ClientSettings\bottom.txt
echo  "DFFlagEnablePerfRenderStatsCollection2": false, >> C:%HOMEPATH%\AppData\Local\Roblox\Versions\%p%\ClientSettings\bottom.txt
echo  "DFFlagEnablePerfStatsCollection3": false, >> C:%HOMEPATH%\AppData\Local\Roblox\Versions\%p%\ClientSettings\bottom.txt
echo  "FFlagReportFpsAndGfxQualityPercentiles": false, >> C:%HOMEPATH%\AppData\Local\Roblox\Versions\%p%\ClientSettings\bottom.txt
echo  "DFFlagAddPublicGettersForGfxQualityAndFpsForTelemCounters": false, >> C:%HOMEPATH%\AppData\Local\Roblox\Versions\%p%\ClientSettings\bottom.txt
echo  "DFIntBrowserTrackerApiDeviceInitializeRolloutPercentage": 0, >> C:%HOMEPATH%\AppData\Local\Roblox\Versions\%p%\ClientSettings\bottom.txt
echo  "DFFlagBrowserTrackerIdTelemetryEnabled": false, >> C:%HOMEPATH%\AppData\Local\Roblox\Versions\%p%\ClientSettings\bottom.txt
echo  "FFlagReportJoinTelemetry": false, >> C:%HOMEPATH%\AppData\Local\Roblox\Versions\%p%\ClientSettings\bottom.txt
echo  "FFlagJoinTimeCounters": false, >> C:%HOMEPATH%\AppData\Local\Roblox\Versions\%p%\ClientSettings\bottom.txt
echo  "FFlagSessionTelemetryApp": false, >> C:%HOMEPATH%\AppData\Local\Roblox\Versions\%p%\ClientSettings\bottom.txt
echo  "DFFlagAddPlaySessionIdTelemetry": false, >> C:%HOMEPATH%\AppData\Local\Roblox\Versions\%p%\ClientSettings\bottom.txt
echo  "DFIntLoginTelemetryHundredthsPercent": 0, >> C:%HOMEPATH%\AppData\Local\Roblox\Versions\%p%\ClientSettings\bottom.txt
echo  "FIntReportDeviceInfoRollout": 0, >> C:%HOMEPATH%\AppData\Local\Roblox\Versions\%p%\ClientSettings\bottom.txt
echo  "DFIntReportDeviceInfoRate": 0, >> C:%HOMEPATH%\AppData\Local\Roblox\Versions\%p%\ClientSettings\bottom.txt
echo  "DFIntReportFmodErrorsRate": 0, >> C:%HOMEPATH%\AppData\Local\Roblox\Versions\%p%\ClientSettings\bottom.txt
echo  "DFFlagAddUserIdToSessionTracking": false, >> C:%HOMEPATH%\AppData\Local\Roblox\Versions\%p%\ClientSettings\bottom.txt
echo  "DFFlagClientBaseNetworkMetrics": false, >> C:%HOMEPATH%\AppData\Local\Roblox\Versions\%p%\ClientSettings\bottom.txt
echo  "DFFlagBaseNetworkMetrics": false, >> C:%HOMEPATH%\AppData\Local\Roblox\Versions\%p%\ClientSettings\bottom.txt
echo  "DFFlagHttpClientRequestMetrics2": false, >> C:%HOMEPATH%\AppData\Local\Roblox\Versions\%p%\ClientSettings\bottom.txt
echo  "DFFlagHttpPointsErrorMetrics": false, >> C:%HOMEPATH%\AppData\Local\Roblox\Versions\%p%\ClientSettings\bottom.txt
echo  "DFFlagHttpPointsResponseMetrics": false, >> C:%HOMEPATH%\AppData\Local\Roblox\Versions\%p%\ClientSettings\bottom.txt
echo  "DFFlagHttpLogRedirects": false, >> C:%HOMEPATH%\AppData\Local\Roblox\Versions\%p%\ClientSettings\bottom.txt
echo  "DFFlagHttpTraceErrorCurrentUrl": false, >> C:%HOMEPATH%\AppData\Local\Roblox\Versions\%p%\ClientSettings\bottom.txt
echo  "DFFlagHttpTraceErrorProxy": false, >> C:%HOMEPATH%\AppData\Local\Roblox\Versions\%p%\ClientSettings\bottom.txt
echo  "DFFlagHttpServiceErrorLogEnabled": false, >> C:%HOMEPATH%\AppData\Local\Roblox\Versions\%p%\ClientSettings\bottom.txt
echo  "DFFlagNewInferredCrashSystem": false, >> C:%HOMEPATH%\AppData\Local\Roblox\Versions\%p%\ClientSettings\bottom.txt
echo  "DFFlagNewInferredCrashSystemV2": false, >> C:%HOMEPATH%\AppData\Local\Roblox\Versions\%p%\ClientSettings\bottom.txt
echo  "DFFlagNewInferredCrashTelemetrySystem": false, >> C:%HOMEPATH%\AppData\Local\Roblox\Versions\%p%\ClientSettings\bottom.txt
echo  "DFFlagInferredCrashMemReportingV2": false, >> C:%HOMEPATH%\AppData\Local\Roblox\Versions\%p%\ClientSettings\bottom.txt
echo  "DFFlagInferredCrashSystemSuccessReportMove": false, >> C:%HOMEPATH%\AppData\Local\Roblox\Versions\%p%\ClientSettings\bottom.txt
echo  "DFIntHttpInfluxHundredthsPercentage": 0, >> C:%HOMEPATH%\AppData\Local\Roblox\Versions\%p%\ClientSettings\bottom.txt
echo  "DFIntHttpInfluxReportsPerMillion": 0, >> C:%HOMEPATH%\AppData\Local\Roblox\Versions\%p%\ClientSettings\bottom.txt
echo  "DFIntHttpGAFailureReportPercent": 0, >> C:%HOMEPATH%\AppData\Local\Roblox\Versions\%p%\ClientSettings\bottom.txt
echo  "DFIntGoogleAnalyticsLoadPlayerHundredth": 0, >> C:%HOMEPATH%\AppData\Local\Roblox\Versions\%p%\ClientSettings\bottom.txt
echo  "DFIntHttpAnalyticsMaxHistory": 0, >> C:%HOMEPATH%\AppData\Local\Roblox\Versions\%p%\ClientSettings\bottom.txt
echo  "FIntRenderShaderLoadAnalyticsHundredthPercent": 0, >> C:%HOMEPATH%\AppData\Local\Roblox\Versions\%p%\ClientSettings\bottom.txt
echo  "FStringImmersiveAdsUniverseWhitelist": "0", >> C:%HOMEPATH%\AppData\Local\Roblox\Versions\%p%\ClientSettings\bottom.txt
echo  "FFlagImmersiveAdsWhitelistDisabled": false, >> C:%HOMEPATH%\AppData\Local\Roblox\Versions\%p%\ClientSettings\bottom.txt
echo  "FFlagEnableAdsAPI": false, >> C:%HOMEPATH%\AppData\Local\Roblox\Versions\%p%\ClientSettings\bottom.txt
echo  "FFlagAdServiceEnabled": false, >> C:%HOMEPATH%\AppData\Local\Roblox\Versions\%p%\ClientSettings\bottom.txt
echo  "DFFlagEnableGCapsHardwareTelemetry": false, >> C:%HOMEPATH%\AppData\Local\Roblox\Versions\%p%\ClientSettings\bottom.txt
echo  "DFFlagAudioDeviceTelemetry": false, >> C:%HOMEPATH%\AppData\Local\Roblox\Versions\%p%\ClientSettings\bottom.txt
echo  "FFlagEnableSoundTelemetry": false, >> C:%HOMEPATH%\AppData\Local\Roblox\Versions\%p%\ClientSettings\bottom.txt
echo  "DFFlagEnableHardwareTelemetry": false, >> C:%HOMEPATH%\AppData\Local\Roblox\Versions\%p%\ClientSettings\bottom.txt
echo  "DFIntHardwareTelemetryHundredthsPercent": 0, >> C:%HOMEPATH%\AppData\Local\Roblox\Versions\%p%\ClientSettings\bottom.txt
echo  "DFFlagEphemeralCounterInfluxReportingEnabled": false, >> C:%HOMEPATH%\AppData\Local\Roblox\Versions\%p%\ClientSettings\bottom.txt
echo  "DFIntEphemeralCounterInfluxReportingPriorityHundredthsPercent": 0, >> C:%HOMEPATH%\AppData\Local\Roblox\Versions\%p%\ClientSettings\bottom.txt
echo  "DFIntEphemeralStatsInfluxReportingPriorityHundredthsPercent": 0, >> C:%HOMEPATH%\AppData\Local\Roblox\Versions\%p%\ClientSettings\bottom.txt
echo  "DFFlagVoiceChatEnableEventCounters3": false, >> C:%HOMEPATH%\AppData\Local\Roblox\Versions\%p%\ClientSettings\bottom.txt
echo  "DFFlagVoiceChatUnderrunErrorsTelemetry": false, >> C:%HOMEPATH%\AppData\Local\Roblox\Versions\%p%\ClientSettings\bottom.txt
echo  "DFFlagVoiceChatHttpResultBodyEmptyTelemetry": false, >> C:%HOMEPATH%\AppData\Local\Roblox\Versions\%p%\ClientSettings\bottom.txt
echo  "FFlagVoiceChatEnableBlockTelemetry": false, >> C:%HOMEPATH%\AppData\Local\Roblox\Versions\%p%\ClientSettings\bottom.txt
echo  "FFlagVoiceChatStatsMultistreamSubscriptionsV2": false, >> C:%HOMEPATH%\AppData\Local\Roblox\Versions\%p%\ClientSettings\bottom.txt
echo  "FFlagEnableFlagRolloutCrashReportingWindows": false, >> C:%HOMEPATH%\AppData\Local\Roblox\Versions\%p%\ClientSettings\bottom.txt
echo  "DFIntLogFileTelemetryInfluxDbHundredthsPercentage": 0, >> C:%HOMEPATH%\AppData\Local\Roblox\Versions\%p%\ClientSettings\bottom.txt
echo  "DFIntLmsClientMaxTargets": 0, >> C:%HOMEPATH%\AppData\Local\Roblox\Versions\%p%\ClientSettings\bottom.txt
echo  "FFlagLocServicePerformanceAnalyticsEnabled": false, >> C:%HOMEPATH%\AppData\Local\Roblox\Versions\%p%\ClientSettings\bottom.txt
echo  "DFFlagDebugAnalyticsSendUserId": false, >> C:%HOMEPATH%\AppData\Local\Roblox\Versions\%p%\ClientSettings\bottom.txt
echo  "DFStringAnalyticsEventStreamUrlEndpoint": "opt-out", >> C:%HOMEPATH%\AppData\Local\Roblox\Versions\%p%\ClientSettings\bottom.txt
echo  "DFStringAltHttpPointsReporterUrl": "https://opt-out.roblox.com", >> C:%HOMEPATH%\AppData\Local\Roblox\Versions\%p%\ClientSettings\bottom.txt
echo  "DFStringAltTelegrafHTTPTransportUrl": "http://opt-out.roblox.com", >> C:%HOMEPATH%\AppData\Local\Roblox\Versions\%p%\ClientSettings\bottom.txt
echo  "DFStringTelegrafHTTPTransportUrl": "https://opt-out.roblox.com", >> C:%HOMEPATH%\AppData\Local\Roblox\Versions\%p%\ClientSettings\bottom.txt
echo  "DFStringLmsRecipeEndpoint": "/opt-out", >> C:%HOMEPATH%\AppData\Local\Roblox\Versions\%p%\ClientSettings\bottom.txt
echo  "DFStringLmsReportEndpoint": "/opt-out", >> C:%HOMEPATH%\AppData\Local\Roblox\Versions\%p%\ClientSettings\bottom.txt
echo  "DFFlagEnableLightstepReporting2": false, >> C:%HOMEPATH%\AppData\Local\Roblox\Versions\%p%\ClientSettings\bottom.txt
echo  "DFIntLightstepHTTPTransportHundredthsPercent2": 0, >> C:%HOMEPATH%\AppData\Local\Roblox\Versions\%p%\ClientSettings\bottom.txt
echo  "DFStringLightstepHTTPTransportUrlHost": "https://opt-out.roblox.com", >> C:%HOMEPATH%\AppData\Local\Roblox\Versions\%p%\ClientSettings\bottom.txt
echo  "DFStringLightstepHTTPTransportUrlPath": "/opt-out", >> C:%HOMEPATH%\AppData\Local\Roblox\Versions\%p%\ClientSettings\bottom.txt
echo  "DFStringLightstepToken": "opt-out", >> C:%HOMEPATH%\AppData\Local\Roblox\Versions\%p%\ClientSettings\bottom.txt
echo  "DFStringHttpPointsReporterUrl": "https://opt-out.roblox.com", >> C:%HOMEPATH%\AppData\Local\Roblox\Versions\%p%\ClientSettings\bottom.txt
echo  "DFStringCrashUploadToBacktraceBaseUrl": "https://opt-out.roblox.com", >> C:%HOMEPATH%\AppData\Local\Roblox\Versions\%p%\ClientSettings\bottom.txt
echo  "FFlagBacktraceMainSourcePathEnabled": false, >> C:%HOMEPATH%\AppData\Local\Roblox\Versions\%p%\ClientSettings\bottom.txt
echo  "FStringErrorUploadToBacktraceBaseUrl": "https://opt-out.roblox.com", >> C:%HOMEPATH%\AppData\Local\Roblox\Versions\%p%\ClientSettings\bottom.txt
echo  "DFFlagReportGlobalAnalyticsUniverseAndPlaceIds": false, >> C:%HOMEPATH%\AppData\Local\Roblox\Versions\%p%\ClientSettings\bottom.txt
echo  "DFStringRobloxAnalyticsSubDomain": "opt-out", >> C:%HOMEPATH%\AppData\Local\Roblox\Versions\%p%\ClientSettings\bottom.txt
echo  "DFStringRobloxAnalyticsURL": "https://opt-out.roblox.com", >> C:%HOMEPATH%\AppData\Local\Roblox\Versions\%p%\ClientSettings\bottom.txt
echo  "DFStringAnalyticsNS1ApplicationId": "opt-out", >> C:%HOMEPATH%\AppData\Local\Roblox\Versions\%p%\ClientSettings\bottom.txt
echo  "DFStringAnalyticsNS1BeaconConfig": "https://opt-out.roblox.com" >> C:%HOMEPATH%\AppData\Local\Roblox\Versions\%p%\ClientSettings\bottom.txt
echo } >> C:%HOMEPATH%\AppData\Local\Roblox\Versions\%p%\ClientSettings\bottom.txt
)
cls
set /p fps=Enter fps:
echo { > C:%HOMEPATH%\AppData\Local\Roblox\Versions\%p%\ClientSettings\ClientAppSettings.json
echo "DFIntTaskSchedulerTargetFps": %fps%, >> C:%HOMEPATH%\AppData\Local\Roblox\Versions\%p%\ClientSettings\ClientAppSettings.json
type C:%HOMEPATH%\AppData\Local\Roblox\Versions\%p%\ClientSettings\bottom.txt >> C:%HOMEPATH%\AppData\Local\Roblox\Versions\%p%\ClientSettings\ClientAppSettings.json
